default_platform(:ios)

 # Вывод значений переменных среды для дебага
 puts "Debugging environment variables:"
 puts "APP_IDENTIFIER: #{ENV['APP_IDENTIFIER']}"
 puts "PROVISIONING_PROFILE_UUID: #{ENV['PROVISIONING_PROFILE_UUID']}"
 puts "SIGNING_CERTIFICATE: #{ENV['SIGNING_CERTIFICATE']}"
 puts "API_KEY_YANDEX_METRICA: #{ENV['API_KEY_YANDEX_METRICA']}"
 puts "API_KEY_APPHUD: #{ENV['API_KEY_APPHUD']}"
 puts "FANCY_BACKEND: #{ENV['FANCY_BACKEND']}"

platform :ios do

  desc "Verify Match profiles for App Store"
  lane :verify_match_appstore do
    match(type: "appstore", readonly: true)
  end

  # Определение базовой директории
  base_directory = ENV['GITHUB_WORKSPACE'] || "." # Если GITHUB_WORKSPACE не определен, используем текущую директорию

  desc "Replace API keys in SecretsAPI.swift"
  lane :replace_api_keys do
    # Извлекаем ключи напрямую, так как они уже установлены GitHub Actions
    api_key_yandex_metrica = ENV["API_KEY_YANDEX_METRICA"]
    api_key_apphud = ENV["API_KEY_APPHUD"]
    fancy_backend = ENV["FANCY_BACKEND"]

    # Заменяем ключи в файле
    replace_api_key_in_file(
      file_path: "#{base_directory}/Avatars/App/Sources/System/SecretsAPI.swift",
      api_key_yandex_metrica: api_key_yandex_metrica,
      api_key_apphud: api_key_apphud,
      fancy_backend: fancy_backend
    )
  end

  desc "Build the app"
  lane :build do

    # Заменяем API-ключи перед сборкой
    replace_api_keys

    build_ios_app(
      workspace: "Avatars.xcworkspace",
      scheme: "Avatars",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_UUID"]
        },
        signingStyle: "manual",
        signingCertificate: ENV["SIGNING_CERTIFICATE"]
      }
    )
  end

  desc "Run unit tests"
  lane :test do
    scan(
      workspace: "Avatars.xcworkspace",
      scheme: "AvatarsTests",
      devices: ["iPhone 12 Pro Max"],
      clean: true
    )
  end

  desc "Upload IPA to App Store Connect"
  lane :upload_app_to_app_store do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      in_house: false,
      is_key_content_base64: true
    )

    pilot(
      api_key: api_key,
      ipa: "Avatars.ipa",
      skip_waiting_for_build_processing: true
    )
  end

  private_lane :replace_api_key_in_file do |options|
    file_path = options[:file_path]
    api_key_yandex_metrica = options[:api_key_yandex_metrica]
    api_key_apphud = options[:api_key_apphud]
    fancy_backend = options[:fancy_backend]

    # Заменяем каждый ключ в файле
    text = File.read(file_path)
    text.gsub!(/apiKeyYandexMetrica = ".*"/, "apiKeyYandexMetrica = \"#{api_key_yandex_metrica}\"")
    text.gsub!(/apiKeyApphud = ".*"/, "apiKeyApphud = \"#{api_key_apphud}\"")
    text.gsub!(/fancyBackend = ".*"/, "fancyBackend = \"#{fancy_backend}\"")
    File.open(file_path, "w") { |file| file.puts text }
  end

end
